<?php
require __DIR__.'/bootstrap.php';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();foreach($_POST['qty']??[] as $id=>$qty){$id=(int)$id;$qty=(int)$qty;if($qty<1)unset($_SESSION['cart'][$id]);else $_SESSION['cart'][$id]=$qty;}if(isset($_POST['remove']))unset($_SESSION['cart'][(int)$_POST['remove']]);flash('success','Your bag has been updated.');redirect('cart.php');}
$pageTitle='Your shopping bag';$cart=$_SESSION['cart']??[];$items=products_by_ids(array_keys($cart));$subtotal=0;foreach($items as $id=>$item)$subtotal+=(float)$item['price']*min((int)$cart[$id],(int)$item['stock']);$freeOver=(float)setting('shipping_free_over','75');$shipping=$subtotal>= $freeOver?0:(float)setting('shipping_flat','4.95');
require __DIR__.'/includes/header.php';
?>
<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="<?= url() ?>">Home</a> / Bag</div><h1>Your shopping bag</h1><p>Review your healthcare supplies before secure PayPal checkout.</p></div></section><section class="section"><div class="container"><?php if(!$items): ?><div class="empty"><h2>Your bag is empty</h2><p>Find quality healthcare essentials in our shop.</p><a class="btn" href="<?= url('shop.php') ?>">Start shopping</a></div><?php else: ?><form method="post" class="cart-layout"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><div><table class="cart-table"><thead><tr><th>Product</th><th>Price</th><th>Quantity</th><th>Total</th><th></th></tr></thead><tbody><?php foreach($items as $id=>$item):$qty=min((int)$cart[$id],(int)$item['stock']); ?><tr><td data-label="Product"><div class="cart-product"><img src="<?= url(e($item['image'])) ?>" alt=""><span><strong><?= e($item['name']) ?></strong><small><?= e($item['sku']) ?></small></span></div></td><td data-label="Price"><?= money((float)$item['price']) ?></td><td data-label="Quantity"><input type="number" name="qty[<?= $id ?>]" min="1" max="<?= (int)$item['stock'] ?>" value="<?= $qty ?>"></td><td data-label="Total"><strong><?= money((float)$item['price']*$qty) ?></strong></td><td><button class="text-link" style="border:0;background:none;cursor:pointer" name="remove" value="<?= $id ?>">Remove</button></td></tr><?php endforeach; ?></tbody></table><button class="btn btn-outline" style="margin-top:20px">Update bag</button></div><aside class="summary-card"><h2>Order summary</h2><div class="summary-line"><span>Subtotal</span><strong><?= money($subtotal) ?></strong></div><div class="summary-line"><span>UK delivery</span><strong><?= $shipping?money($shipping):'Free' ?></strong></div><?php if($shipping): ?><small>Add <?= money($freeOver-$subtotal) ?> more for free delivery.</small><?php endif; ?><div class="summary-line total"><span>Total</span><span><?= money($subtotal+$shipping) ?></span></div><a class="btn btn-dark" href="<?= url('checkout.php') ?>">Continue to checkout</a><a class="text-link" style="display:block;text-align:center;margin-top:16px" href="<?= url('shop.php') ?>">Continue shopping</a></aside></form><?php endif; ?></div></section>
<?php require __DIR__.'/includes/footer.php'; ?>

