<?php
require __DIR__.'/bootstrap.php';$cart=$_SESSION['cart']??[];$items=products_by_ids(array_keys($cart));if(!$items)redirect('cart');
$subtotal=0;foreach($items as $id=>$item)$subtotal+=(float)$item['price']*min((int)$cart[$id],(int)$item['stock']);$shipping=$subtotal>=(float)setting('shipping_free_over','75')?0:(float)setting('shipping_flat','4.95');$total=$subtotal+$shipping;$clientId=setting('paypal_client_id');
$pageTitle='Secure checkout';
ob_start(); if($clientId): ?><script src="https://www.paypal.com/sdk/js?client-id=<?= rawurlencode($clientId) ?>&currency=GBP&intent=capture"></script><script src="<?= url('assets/js/checkout.js') ?>"></script><?php endif; $pageScripts=ob_get_clean();
require __DIR__.'/includes/header.php';
?>
<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="<?= url() ?>">Home</a> / <a href="<?= url('cart.php') ?>">Bag</a> / Checkout</div><h1>Secure checkout</h1><p>Enter your UK delivery details, then complete payment securely with PayPal.</p></div></section><section class="section"><div class="container checkout-layout"><div><h2 style="color:var(--navy);margin-top:0">Delivery details</h2><form id="checkout-form" class="form-grid"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><div class="field"><label for="first_name">First name *</label><input id="first_name" name="first_name" required autocomplete="given-name"></div><div class="field"><label for="last_name">Last name *</label><input id="last_name" name="last_name" required autocomplete="family-name"></div><div class="field"><label for="email">Email *</label><input id="email" type="email" name="email" required autocomplete="email"></div><div class="field"><label for="phone">Phone</label><input id="phone" name="phone" autocomplete="tel"></div><div class="field full"><label for="address">Address *</label><input id="address" name="address" required autocomplete="street-address"></div><div class="field"><label for="city">Town or city *</label><input id="city" name="city" required autocomplete="address-level2"></div><div class="field"><label for="postcode">Postcode *</label><input id="postcode" name="postcode" required autocomplete="postal-code"></div><div class="field full"><label for="notes">Order notes</label><textarea id="notes" name="notes" rows="3"></textarea></div></form><div style="margin-top:25px"><h2 style="color:var(--navy)">Payment</h2><?php if($clientId): ?><div id="checkout-error" class="flash error" hidden></div><div id="paypal-button-container"></div><small>PayPal accepts PayPal balance and eligible debit or credit cards. Your payment details never touch our servers.</small><?php else: ?><div class="paypal-placeholder"><strong>PayPal setup required</strong><br>The shop is ready to take payments once a PayPal client ID and secret are added in Admin → Settings.</div><?php endif; ?></div></div><aside class="summary-card"><h2>Your order</h2><?php foreach($items as $id=>$item):$qty=min((int)$cart[$id],(int)$item['stock']); ?><div class="summary-line"><span><?= e($item['name']) ?> × <?= $qty ?></span><strong><?= money((float)$item['price']*$qty) ?></strong></div><?php endforeach; ?><div class="summary-line"><span>Subtotal</span><strong><?= money($subtotal) ?></strong></div><div class="summary-line"><span>Delivery</span><strong><?= $shipping?money($shipping):'Free' ?></strong></div><div class="summary-line total"><span>Total</span><span><?= money($total) ?></span></div><p style="font-size:12px;color:var(--muted)">Prices are shown in GBP and include applicable VAT.</p></aside></div></section>
<?php require __DIR__.'/includes/footer.php'; ?>
