<?php
require __DIR__.'/bootstrap.php';
$requestedSlug = $_GET['slug'] ?? '';
$legacySlugs = ['privacy'=>'privacy-policy','terms'=>'terms-and-conditions','returns'=>'returns-refund-policy','shipping'=>'shipping-policy','cookies'=>'cookies-policy','disclaimer'=>'media-disclaimer'];
$slug = $legacySlugs[$requestedSlug] ?? $requestedSlug;
$stmt=$db->prepare('SELECT * FROM pages WHERE slug=? AND active=1');$stmt->execute([$slug]);$page=$stmt->fetch();
if(!$page){http_response_code(404);$page=['slug'=>'not-found','title'=>'Page not found','excerpt'=>'The page you requested could not be found.','content'=>'<p>Please return to our homepage or browse the shop.</p>'];}
$pageTitle=$page['title'];$activePage=in_array($page['slug'],['about','faq'],true)?$page['slug']:'';require __DIR__.'/includes/header.php';
?>
<section class="page-hero <?= $page['slug']==='about'?'about-page-hero':'' ?>"><div class="container"><div class="breadcrumbs"><a href="<?= url() ?>">Home</a> / <?= e($page['title']) ?></div><span class="eyebrow">Lurbrook Health</span><h1><?= e($page['title']) ?></h1><p><?= e($page['excerpt']) ?></p></div></section>

<?php if($page['slug']==='about'): ?>
<section class="section about-story-section"><div class="container"><div class="about-story"><article class="prose"><span class="eyebrow">Our story</span><?= $page['content'] ?><div class="about-signoff"><strong>Healthcare supplies, selected with care.</strong><span>Lurbrook Health LTD · United Kingdom</span></div></article><div class="about-mosaic"><img class="about-main" src="<?= url('assets/img/about.png') ?>" alt="Healthcare products selected in a pharmacy" loading="lazy"><img src="<?= url('assets/img/about-pharmacy.jpg') ?>" alt="A stocked pharmacy serving its community" loading="lazy"><img src="<?= url('assets/img/about-supply.jpg') ?>" alt="Healthcare supply shelves" loading="lazy"><div class="about-badge"><strong>UK</strong><span>Nationwide healthcare supply</span></div></div></div><div class="about-metrics"><div><strong>Quality</strong><span>At the centre of every product decision</span></div><div><strong>Reliability</strong><span>Dependable sourcing and responsive support</span></div><div><strong>Partnership</strong><span>Built for organisations, businesses and homes</span></div></div></div></section>
<section class="section section-soft"><div class="container"><div class="section-head center"><span class="eyebrow">Why Lurbrook Health</span><h2>A better standard of healthcare supply</h2><p>We bring practical products and human support together so essential healthcare is easier to access.</p></div><div class="about-values"><article><span>01</span><h3>Quality-led</h3><p>We carefully consider suppliers, products and the documentation that supports them.</p></article><article><span>02</span><h3>Reliable by design</h3><p>Long-term partnerships help us support consistent sourcing and dependable supply.</p></article><article><span>03</span><h3>Customer-focused</h3><p>Straightforward, flexible solutions for organisations, professionals and consumers.</p></article><article><span>04</span><h3>Built to grow</h3><p>A developing Lurbrook range alongside trusted healthcare brands and manufacturing partners.</p></article></div></div></section>
<section class="section"><div class="container"><div class="about-vision"><img src="<?= url('assets/img/about-team.png') ?>" alt="A team collaborating on healthcare supply" loading="lazy"><div><span class="eyebrow">Our direction</span><h2>Growing through trusted partnerships</h2><p>Our ambition is to become a trusted global healthcare brand while staying grounded in responsive service and carefully selected essentials.</p><a class="btn btn-dark" href="<?= url('contact?subject=Supply partnership') ?>">Build a partnership with us →</a></div></div></div></section>
<?php elseif($page['slug']==='faq'): ?>
<section class="section faq-section"><div class="container faq-layout"><div><span class="eyebrow">Answers when you need them</span><h2>How can we help?</h2><p>Browse common questions about ordering, delivery, payments and product support.</p><div class="faq-support"><strong>Still need help?</strong><span>Our team is happy to answer your question.</span><a class="btn btn-dark" href="<?= url('contact') ?>">Contact our team</a></div></div><article class="prose faq-content"><?= $page['content'] ?></article></div></section>
<?php else: ?>
<section class="section"><div class="container content-page"><article class="prose policy-prose"><?= $page['content'] ?></article><aside class="side-card"><h3>Need clarification?</h3><p>Our team can help with questions about this policy or an existing order.</p><a class="btn btn-dark" href="<?= url('contact') ?>">Contact our team</a><a class="btn btn-outline" href="<?= url('faq') ?>">View FAQs</a></aside></div></section>
<?php endif; ?>
<?php require __DIR__.'/includes/footer.php'; ?>
