<?php
require __DIR__.'/bootstrap.php';header('Content-Type: application/json');
if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);echo json_encode(['message'=>'Method not allowed']);exit;}verify_csrf();
$clientId=setting('paypal_client_id');$secret=setting('paypal_secret') ?: ($config['paypal_secret'] ?: (getenv('PAYPAL_SECRET')?:''));$mode=setting('paypal_mode','sandbox');$base=$mode==='live'?'https://api-m.paypal.com':'https://api-m.sandbox.paypal.com';
if(!$clientId||!$secret){http_response_code(503);echo json_encode(['message'=>'PayPal credentials are not configured.']);exit;}
$ch=curl_init($base.'/v1/oauth2/token');curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>'grant_type=client_credentials',CURLOPT_USERPWD=>$clientId.':'.$secret,CURLOPT_HTTPHEADER=>['Accept: application/json','Accept-Language: en_GB'],CURLOPT_TIMEOUT=>30]);$raw=curl_exec($ch);$status=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);$token=json_decode((string)$raw,true)?:[];if($status!==200||empty($token['access_token'])){http_response_code(502);echo json_encode(['message'=>'Could not connect to PayPal.']);exit;}
$access=$token['access_token'];
function paypal_api(string $method,string $url,string $access,?array $payload=null):array{$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>['Content-Type: application/json','Authorization: Bearer '.$access],CURLOPT_TIMEOUT=>30]);if($payload!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($payload));$raw=curl_exec($ch);$status=curl_getinfo($ch,CURLINFO_HTTP_CODE);$error=curl_error($ch);curl_close($ch);$data=json_decode((string)$raw,true)?:[];if($status<200||$status>=300)throw new RuntimeException($data['message']??$error?:'PayPal request failed.');return $data;}
try{
  $cart=$_SESSION['cart']??[];$items=products_by_ids(array_keys($cart));if(!$items)throw new RuntimeException('Your bag is empty.');$subtotal=0;$orderItems=[];foreach($items as $id=>$item){$qty=min((int)$cart[$id],(int)$item['stock']);$subtotal+=(float)$item['price']*$qty;$orderItems[]=['id'=>(int)$id,'name'=>$item['name'],'sku'=>$item['sku'],'quantity'=>$qty,'price'=>(float)$item['price']];}$shipping=$subtotal>=(float)setting('shipping_free_over','75')?0:(float)setting('shipping_flat','4.95');$total=round($subtotal+$shipping,2);
  if(($_GET['action']??'')==='create'){$required=['first_name','last_name','email','address','city','postcode'];foreach($required as $field)if(trim($_POST[$field]??'')==='')throw new RuntimeException('Please complete all delivery details.');if(!filter_var($_POST['email'],FILTER_VALIDATE_EMAIL))throw new RuntimeException('Please enter a valid email address.');$customer=['name'=>trim($_POST['first_name'].' '.$_POST['last_name']),'email'=>trim($_POST['email']),'phone'=>trim($_POST['phone']??''),'address'=>trim($_POST['address']),'city'=>trim($_POST['city']),'postcode'=>strtoupper(trim($_POST['postcode'])),'notes'=>trim($_POST['notes']??'')];$paypal=paypal_api('POST',$base.'/v2/checkout/orders',$access,['intent'=>'CAPTURE','purchase_units'=>[['reference_id'=>'LURBROOK','description'=>'Lurbrook Health order','amount'=>['currency_code'=>'GBP','value'=>number_format($total,2,'.',''),'breakdown'=>['item_total'=>['currency_code'=>'GBP','value'=>number_format($subtotal,2,'.','')],'shipping'=>['currency_code'=>'GBP','value'=>number_format($shipping,2,'.','')]]]]],'application_context'=>['brand_name'=>'Lurbrook Health LTD','shipping_preference'=>'NO_SHIPPING','user_action'=>'PAY_NOW']]);$_SESSION['pending_order']=['paypal_id'=>$paypal['id'],'customer'=>$customer,'items'=>$orderItems,'subtotal'=>$subtotal,'shipping'=>$shipping,'total'=>$total];echo json_encode(['id'=>$paypal['id']]);exit;}
  if(($_GET['action']??'')==='capture'){$pending=$_SESSION['pending_order']??null;if(!$pending||!hash_equals($pending['paypal_id'],(string)($_POST['order_id']??'')))throw new RuntimeException('Order session could not be verified.');$paypal=paypal_api('POST',$base.'/v2/checkout/orders/'.rawurlencode($pending['paypal_id']).'/capture',$access,[]);if(($paypal['status']??'')!=='COMPLETED')throw new RuntimeException('PayPal has not completed this payment.');$paid=(float)($paypal['purchase_units'][0]['payments']['captures'][0]['amount']['value']??0);if(abs($paid-(float)$pending['total'])>.001)throw new RuntimeException('Paid amount does not match the order total.');$number='LH-'.date('ymd').'-'.str_pad((string)random_int(1,9999),4,'0',STR_PAD_LEFT);$c=$pending['customer'];$stmt=$db->prepare('INSERT INTO orders(order_number,paypal_order_id,customer_name,customer_email,customer_phone,address,city,postcode,items,subtotal,shipping,total,payment_status,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$stmt->execute([$number,$pending['paypal_id'],$c['name'],$c['email'],$c['phone'],$c['address'],$c['city'],$c['postcode'],json_encode($pending['items']),$pending['subtotal'],$pending['shipping'],$pending['total'],'paid','processing']);foreach($pending['items'] as $item){$u=$db->prepare('UPDATE products SET stock=MAX(0,stock-?) WHERE id=?');$u->execute([$item['quantity'],$item['id']]);}unset($_SESSION['cart'],$_SESSION['pending_order']);echo json_encode(['success'=>true,'order_number'=>$number]);exit;}
  throw new RuntimeException('Unknown checkout action.');
}catch(Throwable $e){http_response_code(422);echo json_encode(['message'=>$e->getMessage()]);}
