<?php
require __DIR__ . '/bootstrap.php';
$stmt=$db->prepare('SELECT * FROM products WHERE slug=? AND active=1'); $stmt->execute([$_GET['slug']??'']); $product=$stmt->fetch();
if(!$product){http_response_code(404);$pageTitle='Product not found';require __DIR__.'/includes/header.php';echo '<section class="section"><div class="container empty"><h2>Product not found</h2><a class="btn" href="'.url('shop.php').'">Back to shop</a></div></section>';require __DIR__.'/includes/footer.php';exit;}
$pageTitle=$product['name'];$metaDescription=$product['description'];$activePage='shop';
$related=$db->prepare('SELECT * FROM products WHERE active=1 AND category=? AND id!=? ORDER BY featured DESC LIMIT 4');$related->execute([$product['category'],$product['id']]);
require __DIR__.'/includes/header.php';
?>
<section class="section"><div class="container"><div class="breadcrumbs"><a href="<?= url() ?>">Home</a> / <a href="<?= url('shop.php') ?>">Shop</a> / <?= e($product['name']) ?></div><div class="product-detail"><div class="product-main-image"><img src="<?= url(e($product['image'])) ?>" alt="<?= e($product['name']) ?>"></div><div class="product-summary"><span class="product-category"><?= e($product['category']) ?></span><h1><?= e($product['name']) ?></h1><span class="stock <?= $product['stock']<10?'low':'' ?>"><?= $product['stock']>0?e($product['stock'].' in stock'):'Out of stock' ?></span><div class="price" style="font-size:29px;margin:17px 0"><?= money((float)$product['price']) ?><?php if($product['compare_price']>$product['price']): ?><del><?= money((float)$product['compare_price']) ?></del><?php endif; ?></div><p class="lead"><?= e($product['description']) ?></p><ul class="detail-list"><?php foreach(explode('|',$product['details']) as $detail): ?><li><?= e($detail) ?></li><?php endforeach; ?></ul><div class="buy-box"><div class="qty"><button type="button" data-qty="-1">−</button><input id="product-quantity" type="number" min="1" max="<?= (int)$product['stock'] ?>" value="1"><button type="button" data-qty="1">+</button></div><button class="btn btn-dark" data-add-cart="<?= (int)$product['id'] ?>" <?= $product['stock']<1?'disabled':'' ?>>Add to bag</button><p style="font-size:12px;color:var(--muted);margin:13px 0 0">Secure checkout with PayPal · UK-wide delivery</p></div><p style="font-size:12px;color:var(--muted)">SKU: <?= e($product['sku']) ?> · Prices include applicable VAT.</p></div></div></div></section>
<?php $relatedProducts=$related->fetchAll(); if($relatedProducts): ?><section class="section section-soft"><div class="container"><div class="section-head"><div><span class="eyebrow">You may also need</span><h2>Related products</h2></div></div><div class="product-grid"><?php foreach($relatedProducts as $product) require __DIR__.'/includes/product-card.php'; ?></div></div></section><?php endif; ?>
<?php require __DIR__.'/includes/footer.php'; ?>

