<?php
require dirname(__DIR__).'/bootstrap.php';require_admin();
$view=$_GET['view']??'dashboard';
if($_SERVER['REQUEST_METHOD']==='POST'){
  verify_csrf();$action=$_POST['action']??'';
  try{
    if($action==='save_product'){
      $id=(int)($_POST['id']??0);$name=trim($_POST['name']??'');$sku=strtoupper(trim($_POST['sku']??''));if(!$name||!$sku)throw new RuntimeException('Product name and SKU are required.');$image=upload_image('image',trim($_POST['existing_image']??''));if(!$image)throw new RuntimeException('Please upload a product image.');$data=[$name,slugify($_POST['slug']?:$name),trim($_POST['category']),$sku,trim($_POST['description']),implode('|',array_filter(array_map('trim',preg_split('/\r?\n/',$_POST['details']??'')))),max(0,(float)$_POST['price']),($_POST['compare_price']??'')!==''?max(0,(float)$_POST['compare_price']):null,max(0,(int)$_POST['stock']),$image,isset($_POST['featured'])?1:0,isset($_POST['active'])?1:0];
      if($id){$stmt=$db->prepare('UPDATE products SET name=?,slug=?,category=?,sku=?,description=?,details=?,price=?,compare_price=?,stock=?,image=?,featured=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?');$stmt->execute([...$data,$id]);}else{$stmt=$db->prepare('INSERT INTO products(name,slug,category,sku,description,details,price,compare_price,stock,image,featured,active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');$stmt->execute($data);}flash('success',$id?'Product updated successfully.':'Product added successfully.');redirect('admin/?view=products');
    }
    if($action==='delete_product'){$id=(int)$_POST['id'];$stmt=$db->prepare('SELECT image FROM products WHERE id=?');$stmt->execute([$id]);$image=$stmt->fetchColumn();$db->prepare('DELETE FROM products WHERE id=?')->execute([$id]);if($image&&str_starts_with($image,'uploads/')){$path=dirname(__DIR__).'/'.$image;if(is_file($path))unlink($path);}flash('success','Product deleted.');redirect('admin/?view=products');}
    if($action==='save_page'){$stmt=$db->prepare('UPDATE pages SET title=?,excerpt=?,content=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?');$stmt->execute([trim($_POST['title']),trim($_POST['excerpt']),trim($_POST['content']),isset($_POST['active'])?1:0,(int)$_POST['id']]);flash('success','Page content updated.');redirect('admin/?view=pages');}
    if($action==='save_order'){$db->prepare('UPDATE orders SET status=? WHERE id=?')->execute([$_POST['status'],(int)$_POST['id']]);flash('success','Order status updated.');redirect('admin/?view=orders');}
    if($action==='read_message'){$db->prepare("UPDATE messages SET status='read' WHERE id=?")->execute([(int)$_POST['id']]);flash('success','Enquiry marked as read.');redirect('admin/?view=messages');}
    if($action==='delete_message'){$db->prepare('DELETE FROM messages WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Enquiry deleted.');redirect('admin/?view=messages');}
    if($action==='save_settings'){$allowed=['site_name','email','phone','announcement','hero_title','hero_text','shipping_flat','shipping_free_over','paypal_client_id','paypal_mode'];if(trim($_POST['paypal_secret']??'')!=='')$allowed[]='paypal_secret';$stmt=$db->prepare('INSERT INTO settings(setting_key,setting_value) VALUES(?,?) ON CONFLICT(setting_key) DO UPDATE SET setting_value=excluded.setting_value');foreach($allowed as $key)$stmt->execute([$key,trim($_POST[$key]??'')]);flash('success','Store settings saved.');redirect('admin/?view=settings');}
  }catch(Throwable $e){flash('error',$e->getMessage());redirect('admin/?view='.urlencode($view).(!empty($_POST['id'])?'&id='.(int)$_POST['id']:''));}
}

if($view==='product'){
  $section='products';$id=(int)($_GET['id']??0);$product=['id'=>0,'name'=>'','slug'=>'','category'=>'Thermometers','sku'=>'','description'=>'','details'=>'','price'=>'','compare_price'=>'','stock'=>0,'image'=>'','featured'=>1,'active'=>1];if($id){$stmt=$db->prepare('SELECT * FROM products WHERE id=?');$stmt->execute([$id]);$product=$stmt->fetch()?:$product;}$adminTitle=$id?'Edit product':'Add product';require __DIR__.'/_header.php';?>
  <div class="admin-heading"><div><h1><?= $id?'Edit product':'Add a new product' ?></h1><p>Manage product information, stock, pricing and storefront visibility.</p></div><a class="admin-btn light" href="<?= url('admin/?view=products') ?>">← Back to products</a></div>
  <form class="admin-form" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><input type="hidden" name="action" value="save_product"><input type="hidden" name="id" value="<?= (int)$product['id'] ?>"><input type="hidden" name="existing_image" value="<?= e($product['image']) ?>"><div class="form-grid"><div class="field"><label>Product name *</label><input name="name" required value="<?= e($product['name']) ?>"></div><div class="field"><label>URL slug</label><input name="slug" value="<?= e($product['slug']) ?>" placeholder="Generated from product name"></div><div class="field"><label>Category *</label><input name="category" list="categories" required value="<?= e($product['category']) ?>"><datalist id="categories"><option>Thermometers</option><option>Blood Pressure Monitors</option><option>PPE & Masks</option><option>Healthcare Consumables</option><option>Medical Equipment</option></datalist></div><div class="field"><label>SKU *</label><input name="sku" required value="<?= e($product['sku']) ?>"></div><div class="field full"><label>Short description *</label><textarea name="description" rows="3" required><?= e($product['description']) ?></textarea></div><div class="field full"><label>Key features</label><textarea name="details" rows="5" placeholder="One feature per line"><?= e(str_replace('|',"\n",$product['details'])) ?></textarea></div><div class="field"><label>Price (£) *</label><input type="number" name="price" min="0" step="0.01" required value="<?= e((string)$product['price']) ?>"></div><div class="field"><label>Compare-at price (£)</label><input type="number" name="compare_price" min="0" step="0.01" value="<?= e((string)$product['compare_price']) ?>"></div><div class="field"><label>Stock quantity *</label><input type="number" name="stock" min="0" required value="<?= (int)$product['stock'] ?>"></div><div class="field"><label>Product image <?= $id?'':'*' ?></label><input type="file" name="image" accept="image/jpeg,image/png,image/webp,image/avif"><small>JPG, PNG, WebP or AVIF, maximum 6 MB.</small></div><?php if($product['image']): ?><div class="field full"><img src="<?= url(e($product['image'])) ?>" alt="Current image" style="width:110px;height:110px;object-fit:contain;border:1px solid var(--line);border-radius:8px"></div><?php endif; ?><label class="field checkbox"><input type="checkbox" name="featured" <?= $product['featured']?'checked':'' ?>> <span>Feature on homepage</span></label><label class="field checkbox"><input type="checkbox" name="active" <?= $product['active']?'checked':'' ?>> <span>Published and available</span></label></div><div class="form-actions"><button class="admin-btn dark" type="submit"><?= $id?'Save changes':'Publish product' ?></button><a class="admin-btn light" href="<?= url('admin/?view=products') ?>">Cancel</a></div></form>
<?php require __DIR__.'/_footer.php';exit;}

if($view==='page-edit'){
  $section='pages';$stmt=$db->prepare('SELECT * FROM pages WHERE id=?');$stmt->execute([(int)($_GET['id']??0)]);$page=$stmt->fetch();if(!$page)redirect('admin/?view=pages');$adminTitle='Edit '.$page['title'];require __DIR__.'/_header.php';?>
  <div class="admin-heading"><div><h1>Edit <?= e($page['title']) ?></h1><p>Update this website page. Basic HTML headings, paragraphs and lists are supported.</p></div><a class="admin-btn light" target="_blank" href="<?= url('page/'.e($page['slug'])) ?>">Preview page ↗</a></div><form class="admin-form" method="post"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><input type="hidden" name="action" value="save_page"><input type="hidden" name="id" value="<?= (int)$page['id'] ?>"><div class="form-grid"><div class="field"><label>Page title</label><input name="title" required value="<?= e($page['title']) ?>"></div><div class="field"><label>URL slug</label><input value="<?= e($page['slug']) ?>" disabled></div><div class="field full"><label>Intro text</label><textarea name="excerpt" rows="2"><?= e($page['excerpt']) ?></textarea></div><div class="field full"><label>Page content (HTML)</label><textarea name="content" rows="18"><?= e($page['content']) ?></textarea></div><label class="field checkbox"><input type="checkbox" name="active" <?= $page['active']?'checked':'' ?>><span>Page is published</span></label></div><div class="form-actions"><button class="admin-btn dark">Save page</button><a class="admin-btn light" href="<?= url('admin/?view=pages') ?>">Cancel</a></div></form>
<?php require __DIR__.'/_footer.php';exit;}

$adminTitle=ucfirst($view);$section=$view;require __DIR__.'/_header.php';
if($view==='products'){$products=$db->query('SELECT * FROM products ORDER BY updated_at DESC')->fetchAll();?>
<div class="admin-heading"><div><h1>Products</h1><p><?= count($products) ?> products across the Lurbrook Health catalogue.</p></div><a class="admin-btn" href="<?= url('admin/?view=product') ?>">+ Add product</a></div><div class="panel"><table class="admin-table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($products as $p): ?><tr><td><div class="product-cell"><img src="<?= url(e($p['image'])) ?>" alt=""><span><strong><?= e($p['name']) ?></strong><small><?= e($p['sku']) ?></small></span></div></td><td><?= e($p['category']) ?></td><td><strong><?= money((float)$p['price']) ?></strong></td><td><?= (int)$p['stock'] ?><?= $p['stock']<10?' · Low':'' ?></td><td><span class="badge <?= $p['active']?'':'inactive' ?>"><?= $p['active']?'Published':'Hidden' ?></span></td><td><div class="action-links"><a href="<?= url('admin/?view=product&id='.(int)$p['id']) ?>">Edit</a><a target="_blank" href="<?= url('product/'.e($p['slug'])) ?>">View</a><form method="post" onsubmit="return confirm('Delete this product permanently?')"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><input type="hidden" name="action" value="delete_product"><input type="hidden" name="id" value="<?= (int)$p['id'] ?>"><button>Delete</button></form></div></td></tr><?php endforeach; ?></tbody></table></div>
<?php }elseif($view==='orders'){$orders=$db->query('SELECT * FROM orders ORDER BY created_at DESC')->fetchAll();?>
<div class="admin-heading"><div><h1>Orders</h1><p>PayPal payments, fulfilment and customer delivery details.</p></div></div><div class="panel"><?php if(!$orders): ?><div class="empty-admin">No orders yet. Paid orders will appear here automatically.</div><?php else: ?><table class="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Delivery</th><th>Total</th><th>Payment</th><th>Fulfilment</th></tr></thead><tbody><?php foreach($orders as $o): ?><tr><td><strong><?= e($o['order_number']) ?></strong><br><small><?= date('d M Y H:i',strtotime($o['created_at'])) ?></small></td><td><strong><?= e($o['customer_name']) ?></strong><br><small><?= e($o['customer_email']) ?></small></td><td><?= e($o['address']) ?><br><?= e($o['city'].' '.$o['postcode']) ?></td><td><strong><?= money((float)$o['total']) ?></strong><br><small><?= e($o['paypal_order_id']) ?></small></td><td><span class="badge"><?= e($o['payment_status']) ?></span></td><td><form method="post"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><input type="hidden" name="action" value="save_order"><input type="hidden" name="id" value="<?= (int)$o['id'] ?>"><select name="status" onchange="this.form.submit()"><?php foreach(['new','processing','dispatched','delivered','cancelled'] as $status): ?><option <?= $o['status']===$status?'selected':'' ?>><?= $status ?></option><?php endforeach; ?></select></form></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></div>
<?php }elseif($view==='messages'){$messages=$db->query('SELECT * FROM messages ORDER BY created_at DESC')->fetchAll();?>
<div class="admin-heading"><div><h1>Customer enquiries</h1><p>Messages submitted through the website contact form.</p></div></div><div class="panel"><?php if(!$messages): ?><div class="empty-admin">No customer enquiries yet.</div><?php else: ?><table class="admin-table"><thead><tr><th>From</th><th>Subject & message</th><th>Received</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($messages as $m): ?><tr><td><strong><?= e($m['name']) ?></strong><br><a href="mailto:<?= e($m['email']) ?>"><?= e($m['email']) ?></a><br><small><?= e($m['phone']) ?></small></td><td><strong><?= e($m['subject']) ?></strong><p class="message-body"><?= e($m['message']) ?></p></td><td><?= date('d M Y H:i',strtotime($m['created_at'])) ?></td><td><span class="badge <?= e($m['status']) ?>"><?= e($m['status']) ?></span></td><td><div class="action-links"><?php if($m['status']==='unread'): ?><form method="post"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><input type="hidden" name="action" value="read_message"><input type="hidden" name="id" value="<?= (int)$m['id'] ?>"><button>Mark read</button></form><?php endif; ?><form method="post" onsubmit="return confirm('Delete this enquiry?')"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><input type="hidden" name="action" value="delete_message"><input type="hidden" name="id" value="<?= (int)$m['id'] ?>"><button>Delete</button></form></div></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></div>
<?php }elseif($view==='pages'){$pages=$db->query('SELECT * FROM pages ORDER BY title')->fetchAll();?>
<div class="admin-heading"><div><h1>Website pages</h1><p>Edit the main informational and policy content shown on the storefront.</p></div></div><div class="panel"><table class="admin-table"><thead><tr><th>Page</th><th>URL</th><th>Last updated</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($pages as $p): ?><tr><td><strong><?= e($p['title']) ?></strong><br><small><?= e($p['excerpt']) ?></small></td><td>/page/<?= e($p['slug']) ?></td><td><?= date('d M Y H:i',strtotime($p['updated_at'])) ?></td><td><span class="badge <?= $p['active']?'':'inactive' ?>"><?= $p['active']?'Published':'Hidden' ?></span></td><td><div class="action-links"><a href="<?= url('admin/?view=page-edit&id='.(int)$p['id']) ?>">Edit</a><a target="_blank" href="<?= url('page/'.e($p['slug'])) ?>">View</a></div></td></tr><?php endforeach; ?></tbody></table></div>
<?php }elseif($view==='settings'){?>
<div class="admin-heading"><div><h1>Store settings</h1><p>Manage branding copy, customer service, delivery and PayPal.</p></div></div><div class="settings-note"><strong>PayPal:</strong> use sandbox credentials while testing. Switch to live only after replacing both credentials with values from your live PayPal Business app.</div><form class="admin-form" method="post"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><input type="hidden" name="action" value="save_settings"><div class="form-grid"><?php foreach(['site_name'=>'Store name','email'=>'Contact email','phone'=>'Telephone','announcement'=>'Announcement bar','hero_title'=>'Homepage headline','hero_text'=>'Homepage introduction','shipping_flat'=>'Standard delivery (£)','shipping_free_over'=>'Free delivery threshold (£)','paypal_client_id'=>'PayPal client ID'] as $key=>$label): ?><div class="field <?= in_array($key,['announcement','hero_title','hero_text'])?'full':'' ?>"><label><?= $label ?></label><?php if($key==='hero_text'): ?><textarea name="<?= $key ?>" rows="3"><?= e(setting($key)) ?></textarea><?php else: ?><input name="<?= $key ?>" value="<?= e(setting($key)) ?>" <?= str_starts_with($key,'shipping_')?'type="number" min="0" step="0.01"':'' ?>></div><?php endif; ?><?php endforeach; ?><div class="field"><label>PayPal secret</label><input type="password" name="paypal_secret" placeholder="Leave blank to keep the saved secret"><small>The saved secret is never displayed.</small></div><div class="field"><label>PayPal environment</label><select name="paypal_mode"><option value="sandbox" <?= setting('paypal_mode')==='sandbox'?'selected':'' ?>>Sandbox (testing)</option><option value="live" <?= setting('paypal_mode')==='live'?'selected':'' ?>>Live payments</option></select></div></div><div class="form-actions"><button class="admin-btn dark">Save settings</button></div></form>
<?php }else{
  $stats=['products'=>(int)$db->query('SELECT COUNT(*) FROM products WHERE active=1')->fetchColumn(),'stock'=>(int)$db->query('SELECT COALESCE(SUM(stock),0) FROM products WHERE active=1')->fetchColumn(),'orders'=>(int)$db->query('SELECT COUNT(*) FROM orders')->fetchColumn(),'revenue'=>(float)$db->query("SELECT COALESCE(SUM(total),0) FROM orders WHERE payment_status='paid'")->fetchColumn(),'unread'=>(int)$db->query("SELECT COUNT(*) FROM messages WHERE status='unread'")->fetchColumn(),'low'=>(int)$db->query('SELECT COUNT(*) FROM products WHERE active=1 AND stock<10')->fetchColumn()];$recent=$db->query('SELECT * FROM orders ORDER BY created_at DESC LIMIT 6')->fetchAll();$low=$db->query('SELECT * FROM products WHERE active=1 ORDER BY stock ASC LIMIT 5')->fetchAll();?>
<div class="admin-heading"><div><h1>Good <?= date('H')<12?'morning':(date('H')<18?'afternoon':'evening') ?>.</h1><p>Here is what is happening across your Lurbrook Health store.</p></div><a class="admin-btn" href="<?= url('admin/?view=product') ?>">+ Add product</a></div><div class="stat-grid"><div class="stat-card"><small>Paid revenue</small><strong><?= money($stats['revenue']) ?></strong><span>Across <?= $stats['orders'] ?> total orders</span></div><div class="stat-card"><small>Published products</small><strong><?= $stats['products'] ?></strong><span><?= $stats['stock'] ?> units available</span></div><div class="stat-card"><small>Orders</small><strong><?= $stats['orders'] ?></strong><span>Secure PayPal payments</span></div><div class="stat-card"><small>Needs attention</small><strong><?= $stats['unread']+$stats['low'] ?></strong><span><?= $stats['unread'] ?> enquiries · <?= $stats['low'] ?> low stock</span></div></div><div class="admin-grid"><section class="panel"><div class="panel-head"><h2>Recent orders</h2><a href="<?= url('admin/?view=orders') ?>">View all →</a></div><?php if(!$recent): ?><div class="empty-admin">No orders yet. Your first paid order will appear here.</div><?php else: ?><table class="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th></tr></thead><tbody><?php foreach($recent as $o): ?><tr><td><strong><?= e($o['order_number']) ?></strong><br><small><?= date('d M Y',strtotime($o['created_at'])) ?></small></td><td><?= e($o['customer_name']) ?></td><td><strong><?= money((float)$o['total']) ?></strong></td><td><span class="badge <?= e($o['status']) ?>"><?= e($o['status']) ?></span></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></section><aside><section class="panel"><div class="panel-head"><h2>Stock watch</h2><a href="<?= url('admin/?view=products') ?>">Manage →</a></div><div class="quick-list"><?php foreach($low as $p): ?><a href="<?= url('admin/?view=product&id='.(int)$p['id']) ?>"><strong><?= e($p['name']) ?></strong><span><?= (int)$p['stock'] ?> left</span></a><?php endforeach; ?></div></section><section class="panel" style="margin-top:20px"><div class="panel-head"><h2>Quick actions</h2></div><div class="quick-list"><a href="<?= url('admin/?view=pages') ?>">Update website content <span>→</span></a><a href="<?= url('admin/?view=settings') ?>">Configure PayPal <span>→</span></a><a href="<?= url('admin/?view=messages') ?>">Review enquiries <span><?= $stats['unread'] ?></span></a></div></section></aside></div>
<?php } require __DIR__.'/_footer.php';
